audit_header: false
title: Sacramento Real Estate Video Blog with Dan Ellison
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Dan Ellison
  title:
  license_number:
  about_markdown: |
    When it comes to buying or selling a home the key element is to have a strong agent to make sure you are represented properly. You deserve the best and my team and I are here to assist in making sure you get the best outcome in the sale or purchase of your home.

    With me by your side you can expect to get a skilled negotiator who is available when you have questions and who is resourceful with market knowledge and connections in the industry.
  market: Sacramento
  brand: The Dan Ellison Group
  brokerage: Keller Williams
  address: 2277 Fair Oaks Blvd. Ste 195<br>Sacramento, CA 95825
  phone: 916-252-6976
  phone_type:
  phone2:
  phone2_type:
  email: Dan@TeamEllison.com
  url: http://www.HomesInGreaterSacramento.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.homesingreatersacramento.com/homevalue/value
  second_CTA_text: Home Search
  second_CTA_URL: http://www.homesingreatersacramento.com/search

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.homesingreatersacramento.com/homevalue/value

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.homesingreatersacramento.com/search

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/danellisonteam
  linkedin_url: https://www.linkedin.com/in/danellison
  gplus_url: https://plus.google.com/b/105288569752503627385/+Teamellisonsold/about
  youtube_url: https://www.youtube.com/channel/UC4BtEGCTrrp5aBDXzjLPfTA
  twitter_url: https://twitter.com/danellisonteam
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/danellison/
  trulia_url: http://www.trulia.com/profile/dan-ellison-agent-sacramento-ca-zgj14jlv/overview
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/the-dan-ellison-group-real-estate-video-blog/id1229250882?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
